Refactor
Star-Academy/Summer1400-SE-Team16 pull request #1
Opened 2021-07-26 07:08 UTC by AlisaLC

Clean it if you can :D

2021-07-26 08:58 UTC, Kalam132 approved these changes
**Main**:
```
methods could have been in another class
```
**SearchQuery**:
```
using names for regex groups will increase readability
```
**SeachEngine**:
```
throwing an exception might be better(line 43)
getMinimumResultWord is redundant and doesn't improve order complexity as getWordIndexes is called for every word
line 54 is redundant as words with "-" will be removed after processing "+"s
logical issue line(55,58) shouldn't it include results of only "hello" in "hello +hi" command?
duplicate lines(55,58) could be after if else block
```
**Porter Stemmer**:
```
consider splitting stemStep1b into smaller methods(line 41)
consider using more meaningful names for the step methods.
```
well done overall 😄

2021-07-27 12:30 UTC, mostmand requested changes

2021-07-27 12:30 UTC, mostmand commented on Phase01-Search/src/main/java/Main.java
> +        try {
فقط کاربر یه سرچ می‌تونه بکنه؟ بعدش برنامه تموم میشه؟

2021-07-27 12:30 UTC, mostmand commented on Phase01-Search/src/main/java/controller/AppController.java
> +        printResults(results);
پرینت کردن نتایج وظیفه‌ی این کلاس نیست این کلاس صرفاً باید سرچ انجام بده و نتایج رو
return
کنه

2021-07-27 12:30 UTC, mostmand commented on Phase01-Search/src/main/java/model/Document.java
> +    public boolean equals(Object obj) {
وقتی
equals
رو
override
می‌کنید
hashCode
رو هم متناسب با اون
override
کنید

2021-07-27 12:30 UTC, mostmand commented on Phase01-Search/src/main/java/model/SearchQuery.java
> +        Set<String> couldHaveWords = getWordsFromInputByRegex(input, COULD_HAVE_WORDS_REGEX);
یک کد یکسان سه بار تکرار شده می‌تونید تابعش کنید:
```java
this.mustHaveWords = getStemmedSplit(input, MUST_HAVE_WORDS_REGEX);
```
که داریم:
```java
private String[] getStemmedSplit(String input, String patternRegex) {
    Set<String> words = getWordsFromInputByRegex(patternRegex);
    return new DocumentProcessor(words).toStemmedSplit();
}
```

2021-07-27 12:30 UTC, mostmand commented on Phase01-Search/src/main/java/utils/DocumentScanner.java
> +        return new DocumentProcessor(data).toLowerCase().removeSigns().toStemmedSplit();
بهتر نیست به جای این که این‌جا سه تا تابع کال کنید کلاس
DocumentProcessor
یه تابع داشته باشه که همه‌ی این کارارو می‌کنه؟ چون این کلاس انگار وظیفه‌اش صرفاً خوندن داده است و نباید از منطق
normalize
کردن داده اطلاع داشته باشه

2021-07-27 12:30 UTC, mostmand commented on Phase01-Search/src/main/java/utils/SearchEngine.java
> +    public LinkedHashSet<Document> search(SearchQuery query) throws SearchException {
چرا
LinkedHashSet?
مگه ترتیب داکیومنت‌ها اهمیتی داره این‌جا؟

2021-07-27 12:30 UTC, mostmand commented on Phase01-Search/src/main/java/utils/SearchEngine.java
> +            removeMustNotHaveWords(query.getMustNotHaveWords(), resultsSet);
اگه چنین کوئری زده بشه کد شما چه خروجی داره؟
-hello

2021-07-27 12:30 UTC, mostmand commented on Phase01-Search/src/main/java/utils/SearchEngine.java
>              for (String word : couldHaveWords) {
فور داخل یه فور دیگه خوب نیست کد رو ناخوانا می‌کنه به عنوان تابع استخراجش کنید

2021-07-27 12:30 UTC, mostmand commented on Phase01-Search/src/main/java/utils/SearchEngine.java
> +        if (isArrayNotEmpty(mustNotHaveWords)) {
از
guard clause
استفاده کنید تا کد خواناتر بشه
https://refactoring.guru/replace-nested-conditional-with-guard-clauses
```java
if (isArrayEmpty) {
    return;
}
...
```

2021-07-27 17:42 UTC, AlisaLC commented on Phase01-Search/src/main/java/utils/SearchEngine.java
> +            removeMustNotHaveWords(query.getMustNotHaveWords(), resultsSet);
همون ست خروجی تابع اول که یه ست خالی هست ریترن میشه

2021-07-27 17:43 UTC, AlisaLC commented on Phase01-Search/src/main/java/utils/SearchEngine.java
> +    public LinkedHashSet<Document> search(SearchQuery query) throws SearchException {
می خواستم در مرحله بعد بر حسب تعداد کلمه های + دار داخل داکیومنت سورت کنم خروجی بدم

2021-07-27 17:49 UTC, AlisaLC commented on Phase01-Search/src/main/java/Main.java
> +        try {
بله بعد سرچ اول تموم میشه
چون زمان ایندکسینگش زیاد نبود موقع تست راحت تر بود
داخل حلقه هم میشه گذاشتش فرق خاصی نمی کنه

2021-08-16 03:53 UTC, mostmand approved these changes

2021-08-16 04:54 UTC, merged